### PR TITLE
support edgex 2.1

### PR DESCRIPTION
**Pull request by wawlian**
What type of PR is this?
Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind feature
/sig iot

What this PR does / why we need it:
Supports EdgeX Foundry Jakarta Version. EdgeX Jakarta is the first LTS version and be widely considered as a production ready version.

Which issue(s) this PR fixes:
None

Does this PR introduce a user-facing change?
Yes。Since EdgeX Jakarta version switched to api v2, so not only the internal interaction logic between OpenYurt and EdgeX, but also the CRDs changed accordingly. The mainly user-facing changes are list as below:

We removed ValueDescriptor CRD
Some fields of Device、DeviceService、DeviceProfile has changed，users can refer to the CRD yamls in the config/crd/bases directory
1. Supports EdgeX 2.1 integration.
2. Adjust CRDs of Device、DeviceService、DeviceProfile.
3. Removed ValueDescriptor.

### CODE REVIEW

**Review by qclc — COMMENTED** [review]
Please apply the modification of CRD to the [crd.yaml](https://github.com/openyurtio/yurt-device-controller/blob/main/config/setup/crd.yaml) file (this file is used by users to quickly deploy the CRD related to yurt-device-controller in the cluster) @wawlian

**Comment by wawlian** [comment]
@qclc  crd file updated

**Pull request merged**
